name: Node.js CI-CD dev

on:
  push:
    branches: [develop]
  # pull_request:
  #   branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies and run tests suite
        run: yarn
      - run: yarn build
      #- run: npm test
      #Seeds
      - name: Run Migrations and Seeds
        run: |
          npx prisma migrate deploy
          npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
          NODE_ENV: dev
      #Deploy to heroku
      - name: Depoy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "detoxify-back-dev" #Must be unique in Heroku
          heroku_email: "nacho.conso@gmail.com"
          healthcheck: "https://detoxify-back-dev.herokuapp.com/health"
          delay: 5
          rollbackonhealthcheckfailed: true
